### PR TITLE
Bugfix/295 fix styles and remove double fetching

### LINKED ISSUE #295: fix styles add remove double fetching
Fix bugs on stepper

### PR DESCRIPTION
**Pull request by NataliiaDanchenko**
## Summary by CodeRabbit

- **Bug Fixes**
  - Improved category and subject selection to prevent duplicate entries and ensure correct deletion of subjects.
  - Fixed state handling issues to enhance reliability during category loading and pagination.

- **Style**
  - Updated layout and spacing for better responsiveness across devices.
  - Adjusted image sizes and container widths for improved visual consistency.

- **Chores**
  - Removed outdated mock data to ensure all categories and subjects are dynamically loaded.

### CODE REVIEW

**Review by yrudikov — APPROVED** [review]

**Review by ssashayurchenko — APPROVED** [review]

**Review by pavlo1377 — APPROVED** [review]

**Review by tanichk4 — APPROVED** [review]

**Review by oksana0145 — APPROVED** [review]

File: src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx [hunk 1]
```diff
@@ -119,14 +56,16 @@ const SubjectsStep = ({ btnsBox }) => {
...
-      })
       .catch((error) => {
-        console.error('Error category download:', error)
+        console.error('Error fetching categories:', error)
+      })
+      .finally(() => {
+        setCategoriesLoaded(false)
       })
-  }, [page, fetchCategories, setCategoriesLoaded])
+  }, [page, fetchCategories])
```
Comment (vlad-khrychov) [inline src/containers/tutor-home-page/subjects-step/SubjectsStep.jsx:68]:
```suggestion
  }, [page, fetchCategories, categoriesLoaded])
```

**Review by vlad-khrychov — CHANGES_REQUESTED** [review]
