### PR TITLE
 Conflict in PopupDialog resolved

### LINKED ISSUE #247: Conflict in PopupDialog
There is a conflict in the PopupDialog.jsx file.

Image

this function needs to be removed from the file as it causes unexpected behavior

### PR DESCRIPTION
**Pull request by pavlo1377**
Resolved conflic in the PopupDialog compnent

Removed backdrop click close handler

## Summary by CodeRabbit

- **Refactor**
  - Simplified dialog behavior by removing custom handling for closing the dialog via backdrop clicks. The dialog no longer responds to backdrop click events for closing.

### CODE REVIEW

**Review by yrudikov — APPROVED** [review]

**Review by oksana0145 — APPROVED** [review]

**Review by NataliiaDanchenko — APPROVED** [review]

**Review by VoroninaMaria — APPROVED** [review]

File: src/components/popup-dialog/PopupDialog.tsx [hunk 1]
```diff
@@ -50,13 +50,6 @@ const PopupDialog: FC<PopupDialogProps> = ({
     }
   }
 
-  const handleDialogClose = (_event: object, reason: string) => {
-    if (reason === 'backdropClick') {
-      handleClose()
-    }
-    return
-  }
-
```
Comment (vlad-khrychov) [inline src/components/popup-dialog/PopupDialog.tsx:59]: I saw this code in one of previous PR. Should we add or remove it?

**Review by vlad-khrychov — APPROVED** [review]

File: src/components/popup-dialog/PopupDialog.tsx (hunk 1 above)
Comment (pavlo1377) [reply src/components/popup-dialog/PopupDialog.tsx:59]: We should remove it.
After running into conflict with some implementations of this component, our team decided to isolate this logic into components where this functionality is needed.

Eventually, the final PopupDialog code is expected to have these lines of code deleted.
