### PR TITLE
Bugfix/241/fix any type errors

### LINKED ISSUE #241: Fix errors related to the 'any' type
Pull request gives "type any" errors:
Image

Image

Image

### PR DESCRIPTION
**Pull request by yrudikov**
Fixed type errors in project

image

## Summary by CodeRabbit

- **New Features**
  - Added support for managing attachments, lessons, and quizzes, including new types and service methods for these resources.
  - Introduced a new "Attachments" tab for resource management.

- **Improvements**
  - Updated interface definitions for educational content, resources, and attachments to support richer resource data.
  - Enhanced service capabilities to handle lessons, quizzes, and attachments.

- **Bug Fixes**
  - Adjusted resource filtering logic to exclude items without a title property from search results.

- **Style**
  - Minor formatting and import path adjustments for improved code consistency.

### CODE REVIEW

**Review by pavlo1377 — APPROVED** [review]

File: src/types/my-resources/interfaces/myResources.interface.ts [hunk 1]
```diff
@@ -18,3 +25,44 @@ export interface UpdateResourceCategory {
...
+  description: string
+  content: string
+  attachments: Attachment[]
+  category: string | null
+}
+
+export interface CourseResources extends CommonEntityFields {
+  title: string
+  text: string
+  answers: Answer[]
```
Comment (ssashayurchenko) [inline src/types/my-resources/interfaces/myResources.interface.ts:56]: можна було б додати тип null щоб передбачити відсутність відповідей:
```suggestion
  answers: Answer[] | null
```

**Review by ssashayurchenko — APPROVED** [review]

**Review by tanichk4 — APPROVED** [review]

**Review by bohuslavstan — APPROVED** [review]
approved

**Review by vlad-khrychov — APPROVED** [review]
