### PR TITLE
#229-fixed-logo-navigation

### LINKED ISSUE #229: [Home page] The “Space2Study” logo button does not return to the home page welcoming block after clicking it.
**Description**: The “Space2Study” logo button does not return to the home page welcoming block after clicking it.

**Environment**: Windows 10 x64, Microsoft Edge 112.0.1722.48, Google Chrome 112.0.5615.122, MacOS Big Sur 11.7.3 Safari 16.3 (16614.4.6.11.6, 16614)

**Reproducible**: always.

**Preconditions:**
The site is opened.
The user is not logged in.

**Steps to reproduce:**
1. Scroll down to the “How it works” block on the home page.
2. Click on the “Space2Study” logo button on the header.
3. Take a look at the home page.

**Actual result:**
The “Space2Study” logo button does **NOT** return to the home page welcoming block after clicking it.
**Expected result:**
The system scrolls back to the home page welcoming block after clicking on the “Space2Study” logo button on the header.

### PR DESCRIPTION
**Pull request by ssashayurchenko**
Fixed the issue where clicking the “Space2Study” logo button did not scroll back to the welcoming block on the home page. Now, the system correctly scrolls to the top section when the logo is clicked.

## Summary by CodeRabbit

- **New Features**
  - The logo is now a clickable element that smoothly directs users to a designated section, enhancing intuitive navigation with a clear pointer style on hover.

### CODE REVIEW

**Review by pavlo1377 — APPROVED** [review]
looks good! approve

**Review by yrudikov — APPROVED** [review]
Looks good)

**Review by NataliiaDanchenko — APPROVED** [review]

**Comment by oksana0145** [comment]
Great!

**Review by tanichk4 — APPROVED** [review]
Looking great!

**Review by oksana0145 — APPROVED** [review]

File: src/containers/logo/Logo.tsx [hunk 1]
```diff
@@ -8,13 +8,24 @@ interface LogoProps extends BoxProps {
...
-  <Box
-    alt='logo'
-    component={ComponentEnum.Img}
-    src={light ? logoLight : logo}
-    {...props}
-  />
-)
+const Logo: FC<LogoProps> = ({ light = false, ...props }) => {
+  const handleClick = () => {
+    const welcomeSection = document.querySelector('[data-route="welcome"]')
```
Comment (vlad-khrychov) [inline src/containers/logo/Logo.tsx]: Using `querySelector` in a React application is not a best practice. Also take a look at the `HashLink` component.

**Review by vlad-khrychov — CHANGES_REQUESTED** [review]

**Review by oksana0145 — APPROVED** [review]

**Review by vlad-khrychov — APPROVED** [review]
